export const SET_PROPERTY_INFO = "SET_PROPERTY_INFO";
export const RESET_PROPERTY_INFO = "RESET_PROPERTY_INFO";
export const ADD_TO_ARRAY = "ADD_TO_ARRAY";
export const REMOVE_FROM_ARRAY = "REMOVE_FROM_ARRAY";
export const SET_INITIAL_DEFAULT_INFO = "SET_INITIAL_DEFAULT_INFO";